### ISSUE TITLE
TransType from FontLab (paid)

### ISSUE THREAD

**Issue by tcaddy** [Jolg42/awesome-typography#14]
I have used this paid product on a Mac computer to convert .ps (postscript) fonts to .ttf (TrueType) fonts.

It was a lifesaver working on Adobe suite products on a Windows computer using projects that were created and packaged on a Mac.

https://www.fontlab.com/font-converter/transtype/

**Comment by Jolg42** [comment]
Thanks!
It's in the README 😉
